//! `/etc/fstab`: which Windows directories the shell sees, and under what name.
//!
//! Three things are mounted, and no more:
//!
//! - `none / cygdrive` drops the `/cygdrive` prefix, so drives are `/c`, `/d`;
//! - `/pm3` is `$HOME` inside the shell and where proxmark3 sources live;
//! - `/builds` is the output of `autobuild`, and only that command asks for it.
//!
//! The original also mounted `/setup`; here the assets live inside the tree at
//! `/opt/proxspace`, so there is nothing outside it left to reach for.
//!
//! The file is rewritten whole every time, exactly as the original did. It is
//! ours, its contents follow from the install path alone, and merging into
//! whatever a previous version or a curious user left behind would cost more
//! than it could ever be worth.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use thiserror::Error;

use crate::core::paths::Paths;
use crate::ui::Ui;

/// Location inside the msys2 tree.
pub const FSTAB_PATH: &str = "etc/fstab";

/// Mount options shared by every real directory we map in.
///
/// `noacl` stops cygwin translating POSIX permissions into NTFS ACLs. Without
/// it every `chmod` in a build turns into ACL edits: slow, and wrong often
/// enough to break builds outright.
const MOUNT_OPTIONS: &str = "ntfs noacl 0 0";

#[derive(Debug, Error)]
pub enum FstabError {
    #[error("cannot create `{path}`")]
    CreateDir {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("cannot write `{path}`")]
    Write {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
}

/// What the shell should be able to see.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mounts {
    /// Windows path mounted as `/pm3`.
    pub pm3: PathBuf,
    /// Windows path mounted as `/builds`, when `autobuild` needs it.
    pub builds: Option<PathBuf>,
}

impl Mounts {
    /// The mounts for an installation, with `/builds` left out.
    pub fn for_paths(paths: &Paths) -> Mounts {
        Mounts {
            pm3: paths.pm3(),
            builds: None,
        }
    }

    /// The same, plus the `autobuild` output directory.
    pub fn with_builds(paths: &Paths) -> Mounts {
        Mounts {
            pm3: paths.pm3(),
            builds: Some(paths.builds()),
        }
    }
}

/// The complete contents of `/etc/fstab` for these mounts.
pub fn render(mounts: &Mounts) -> String {
    let mut text = String::new();
    text.push_str(
        "# /etc/fstab, generated by ProxSpace. Every run rewrites it whole, so edits\n\
         # made here are lost. For the file format, see the cygwin Users Guide:\n\
         # http://cygwin.com/cygwin-ug-net/using.html#mount-table\n\
         \n\
         # Drives as /c, /d ... rather than /cygdrive/c.\n\
         none / cygdrive binary,posix=0,noacl,user 0 0\n",
    );

    text.push_str("\n# $HOME inside the shell, and where the proxmark3 sources are checked out.\n");
    text.push_str(&entry(&mounts.pm3, "/pm3"));

    if let Some(builds) = &mounts.builds {
        text.push_str(
            "\n# Output of `proxspace autobuild`, mounted only while that command runs.\n",
        );
        text.push_str(&entry(builds, "/builds"));
    }

    text
}

/// One mount line.
fn entry(windows_path: &Path, mount_point: &str) -> String {
    format!(
        "{} {mount_point} {MOUNT_OPTIONS}\n",
        escape(&windows_path.to_string_lossy())
    )
}

/// Escape a path for the first field of an fstab line.
///
/// Fields are separated by whitespace, so whitespace inside a path has to be
/// written as an octal escape — cygwin reads `\040` back as a space. The
/// install path is validated well before this point and cannot contain any of
/// it, but fstab is generated from a path the user chose, and a silent
/// mis-parse here would mount the wrong directory rather than fail.
fn escape(path: &str) -> String {
    path.chars()
        .map(|character| match character {
            ' ' => "\\040".to_string(),
            '\t' => "\\011".to_string(),
            other => other.to_string(),
        })
        .collect()
}

/// Write `/etc/fstab` into the tree, returning whether anything changed.
pub fn install(root: &Path, mounts: &Mounts, ui: &Ui) -> Result<bool, FstabError> {
    let destination = root.join(FSTAB_PATH);
    let contents = render(mounts);

    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent).map_err(|source| FstabError::CreateDir {
            path: parent.to_path_buf(),
            source,
        })?;
    }

    if fs::read(&destination).is_ok_and(|existing| existing == contents.as_bytes()) {
        return Ok(false);
    }

    fs::write(&destination, contents.as_bytes()).map_err(|source| FstabError::Write {
        path: destination.clone(),
        source,
    })?;
    ui.detail(&format!("wrote `{}`", destination.display()));
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    const BASIC: &str = include_str!("../../../tests/fixtures/fstab-basic");
    const WITH_BUILDS: &str = include_str!("../../../tests/fixtures/fstab-with-builds");

    fn silent_ui() -> Ui {
        Ui::new(
            crate::ui::UiOptions {
                quiet: true,
                ..crate::ui::UiOptions::default()
            },
            Arc::new(crate::ui::logging::Logger::disabled()),
        )
    }

    fn mounts(builds: bool) -> Mounts {
        Mounts {
            pm3: PathBuf::from(r"C:\ProxSpace\pm3"),
            builds: builds.then(|| PathBuf::from(r"C:\ProxSpace\builds")),
        }
    }

    /// Fixtures are stored with LF; a checkout that converted them anyway must
    /// not be able to fail the comparison for a reason nobody cares about.
    fn fixture(text: &str) -> String {
        text.replace("\r\n", "\n")
    }

    #[test]
    fn the_plain_case_matches_the_reference() {
        assert_eq!(render(&mounts(false)), fixture(BASIC));
    }

    #[test]
    fn autobuild_adds_the_builds_mount() {
        assert_eq!(render(&mounts(true)), fixture(WITH_BUILDS));
    }

    #[test]
    fn the_cygdrive_prefix_is_always_dropped() {
        // Without this line every drive is /cygdrive/c and half the paths in
        // the proxmark3 makefiles stop resolving.
        assert!(render(&mounts(false)).contains("none / cygdrive binary,posix=0,noacl,user 0 0\n"));
    }

    #[test]
    fn setup_is_not_mounted_any_more() {
        assert!(!render(&mounts(true)).contains("/setup"));
    }

    #[test]
    fn every_mount_line_has_the_six_fields_cygwin_expects() {
        for line in render(&mounts(true))
            .lines()
            .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        {
            assert_eq!(
                line.split_whitespace().count(),
                6,
                "malformed mount line: {line}"
            );
        }
    }

    #[test]
    fn whitespace_in_a_path_is_escaped_rather_than_splitting_the_line() {
        let awkward = Mounts {
            pm3: PathBuf::from(r"C:\Program Files\ProxSpace\pm3"),
            builds: None,
        };
        let rendered = render(&awkward);

        assert!(rendered.contains(r"C:\Program\040Files\ProxSpace\pm3 /pm3"));
        for line in rendered
            .lines()
            .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        {
            assert_eq!(line.split_whitespace().count(), 6);
        }
    }

    #[test]
    fn escaping_leaves_ordinary_paths_alone() {
        assert_eq!(escape(r"C:\ProxSpace\pm3"), r"C:\ProxSpace\pm3");
        assert_eq!(escape("a\tb"), r"a\011b");
    }

    #[test]
    fn writing_creates_etc_on_the_way() {
        let dir = tempfile::tempdir().unwrap();

        assert!(install(dir.path(), &mounts(false), &silent_ui()).unwrap());

        let written = fs::read_to_string(dir.path().join(FSTAB_PATH)).unwrap();
        assert_eq!(written, fixture(BASIC));
    }

    #[test]
    fn writing_the_same_mounts_twice_changes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        install(dir.path(), &mounts(false), &silent_ui()).unwrap();

        assert!(!install(dir.path(), &mounts(false), &silent_ui()).unwrap());
    }

    #[test]
    fn a_foreign_fstab_is_replaced_whole() {
        let dir = tempfile::tempdir().unwrap();
        let destination = dir.path().join(FSTAB_PATH);
        fs::create_dir_all(destination.parent().unwrap()).unwrap();
        fs::write(&destination, "C:\\elsewhere /setup ntfs noacl 0 0\n").unwrap();

        assert!(install(dir.path(), &mounts(false), &silent_ui()).unwrap());

        let written = fs::read_to_string(&destination).unwrap();
        assert_eq!(written, fixture(BASIC));
        assert!(!written.contains("elsewhere"));
    }

    #[test]
    fn adding_and_removing_the_builds_mount_both_take_effect() {
        let dir = tempfile::tempdir().unwrap();
        install(dir.path(), &mounts(false), &silent_ui()).unwrap();

        assert!(install(dir.path(), &mounts(true), &silent_ui()).unwrap());
        assert!(
            fs::read_to_string(dir.path().join(FSTAB_PATH))
                .unwrap()
                .contains("/builds")
        );

        // The original left the /builds line behind for exactly one run; here
        // it goes away as soon as the command that wanted it is over.
        assert!(install(dir.path(), &mounts(false), &silent_ui()).unwrap());
        assert!(
            !fs::read_to_string(dir.path().join(FSTAB_PATH))
                .unwrap()
                .contains("/builds")
        );
    }

    #[test]
    fn mounts_come_from_the_install_paths() {
        let dir = tempfile::tempdir().unwrap();
        let paths = crate::infra::paths::from_dir(dir.path()).unwrap();

        assert_eq!(Mounts::for_paths(&paths).pm3, paths.pm3());
        assert_eq!(Mounts::for_paths(&paths).builds, None);
        assert_eq!(Mounts::with_builds(&paths).builds, Some(paths.builds()));
    }
}
