//! What the shell sees where: the mount table ProxSpace writes into the tree.
//!
//! cygwin reads `/etc/fstab` once per installation, so the file is rendered
//! whole rather than edited, and what it should say is worked out here without
//! touching the disk.

use std::path::{Path, PathBuf};

use crate::core::paths::Paths;

/// Location inside the msys2 tree.
pub const FSTAB_PATH: &str = "etc/fstab";

/// Mount options shared by every real directory we map in.
///
/// `noacl` stops cygwin translating POSIX permissions into NTFS ACLs. Without
/// it every `chmod` in a build turns into ACL edits: slow, and wrong often
/// enough to break builds outright.
const MOUNT_OPTIONS: &str = "ntfs noacl 0 0";

/// What the shell should be able to see.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mounts {
    /// Windows path mounted as `/pm3`.
    pub pm3: PathBuf,
    /// Windows path mounted as `/builds`, when `autobuild` needs it.
    pub builds: Option<PathBuf>,
}

impl Mounts {
    /// The mounts for an installation, with `/builds` left out.
    pub fn for_paths(paths: &Paths) -> Mounts {
        Mounts {
            pm3: paths.pm3(),
            builds: None,
        }
    }

    /// The same, plus the `autobuild` output directory.
    pub fn with_builds(paths: &Paths) -> Mounts {
        Mounts {
            pm3: paths.pm3(),
            builds: Some(paths.builds()),
        }
    }
}

/// The complete contents of `/etc/fstab` for these mounts.
pub fn render(mounts: &Mounts) -> String {
    let mut text = String::new();
    text.push_str(
        "# /etc/fstab, generated by ProxSpace. Every run rewrites it whole, so edits\n\
         # made here are lost. For the file format, see the cygwin Users Guide:\n\
         # http://cygwin.com/cygwin-ug-net/using.html#mount-table\n\
         \n\
         # Drives as /c, /d ... rather than /cygdrive/c.\n\
         none / cygdrive binary,posix=0,noacl,user 0 0\n",
    );

    text.push_str("\n# $HOME inside the shell, and where the proxmark3 sources are checked out.\n");
    text.push_str(&entry(&mounts.pm3, "/pm3"));

    if let Some(builds) = &mounts.builds {
        text.push_str(
            "\n# Output of `proxspace autobuild`, mounted only while that command runs.\n",
        );
        text.push_str(&entry(builds, "/builds"));
    }

    text
}

/// One mount line.
fn entry(windows_path: &Path, mount_point: &str) -> String {
    format!(
        "{} {mount_point} {MOUNT_OPTIONS}\n",
        escape(&windows_path.to_string_lossy())
    )
}

/// Escape a path for the first field of an fstab line.
///
/// Fields are separated by whitespace, so whitespace inside a path has to be
/// written as an octal escape — cygwin reads `\040` back as a space. The
/// install path is validated well before this point and cannot contain any of
/// it, but fstab is generated from a path the user chose, and a silent
/// mis-parse here would mount the wrong directory rather than fail.
fn escape(path: &str) -> String {
    path.chars()
        .map(|character| match character {
            ' ' => "\\040".to_string(),
            '\t' => "\\011".to_string(),
            other => other.to_string(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    use std::path::PathBuf;

    const BASIC: &str = include_str!("../../tests/fixtures/fstab-basic");
    const WITH_BUILDS: &str = include_str!("../../tests/fixtures/fstab-with-builds");

    fn mounts(builds: bool) -> Mounts {
        Mounts {
            pm3: PathBuf::from(r"C:\ProxSpace\pm3"),
            builds: builds.then(|| PathBuf::from(r"C:\ProxSpace\builds")),
        }
    }

    fn fixture(text: &str) -> String {
        text.replace("\r\n", "\n")
    }

    #[test]
    fn the_plain_case_matches_the_reference() {
        assert_eq!(render(&mounts(false)), fixture(BASIC));
    }

    #[test]
    fn autobuild_adds_the_builds_mount() {
        assert_eq!(render(&mounts(true)), fixture(WITH_BUILDS));
    }

    #[test]
    fn the_cygdrive_prefix_is_always_dropped() {
        // Without this line every drive is /cygdrive/c and half the paths in
        // the proxmark3 makefiles stop resolving.
        assert!(render(&mounts(false)).contains("none / cygdrive binary,posix=0,noacl,user 0 0\n"));
    }

    #[test]
    fn setup_is_not_mounted_any_more() {
        assert!(!render(&mounts(true)).contains("/setup"));
    }

    #[test]
    fn every_mount_line_has_the_six_fields_cygwin_expects() {
        for line in render(&mounts(true))
            .lines()
            .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        {
            assert_eq!(
                line.split_whitespace().count(),
                6,
                "malformed mount line: {line}"
            );
        }
    }

    #[test]
    fn whitespace_in_a_path_is_escaped_rather_than_splitting_the_line() {
        let awkward = Mounts {
            pm3: PathBuf::from(r"C:\Program Files\ProxSpace\pm3"),
            builds: None,
        };
        let rendered = render(&awkward);

        assert!(rendered.contains(r"C:\Program\040Files\ProxSpace\pm3 /pm3"));
        for line in rendered
            .lines()
            .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        {
            assert_eq!(line.split_whitespace().count(), 6);
        }
    }

    #[test]
    fn escaping_leaves_ordinary_paths_alone() {
        assert_eq!(escape(r"C:\ProxSpace\pm3"), r"C:\ProxSpace\pm3");
        assert_eq!(escape("a\tb"), r"a\011b");
    }

    #[test]
    fn mounts_come_from_the_install_paths() {
        let paths = Paths::new(PathBuf::from(r"C:\ProxSpace"));

        assert_eq!(Mounts::for_paths(&paths).pm3, paths.pm3());
        assert_eq!(Mounts::for_paths(&paths).builds, None);
        assert_eq!(Mounts::with_builds(&paths).builds, Some(paths.builds()));
    }
}
